# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BannerDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_design_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('event_logo', models.CharField(max_length=200)),
                ('event_organizer', models.CharField(max_length=200)),
                ('event_custom_title', models.CharField(max_length=200)),
                ('enven_custom_logo', models.CharField(max_length=200)),
                ('event_custom_description', models.TextField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.Banner')),
            ],
        ),
        migrations.CreateModel(
            name='EventDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_design_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_design_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.EventDesign'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.BannerDesign'),
        ),
        migrations.AddField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
