# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.BannerDesign'),
        ),
        migrations.AlterField(
            model_name='event',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.EventDesign'),
        ),
    ]
