# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20180328_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerdesign',
            name='data_rotate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='data_scale',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='data_x',
            field=models.IntegerField(default=-2000, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='data_y',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='data_z',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='multiplier_x',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='multiplier_y',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bannerdesign',
            name='multiplier_z',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bannerdesign',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
