# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20180403_1157'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO auth_user("password",' +
            '"is_superuser","username","first_name","last_name",' +
            '"email","is_staff","is_active","date_joined") VALUES ' +
            '(\'pbkdf2_sha256$36000$JhbgNrVdAcAY$pgZRYe/6Fv0LDo' +
            's5RiSnvjPbiv9MMmdVy75KOhDsNhQ=\',TRUE,\'admin\',\'\',' +
            '\'\',\'\',TRUE,TRUE,' +
            '\'2018-04-04 11:44:19.781901-03\');'
        ),

        migrations.RunSQL(
            'INSERT INTO banner_bannerdesign("name","created","changed"' +
            ',"user_id",' + '"data_rotate","data_scale","data_x",' +
            '"data_y","data_z","multiplier_x","multiplier_y","multiplier_z")' +
            'VALUES (\'horizontal layout\',\'2018-04-04 11:57:38' +
            '.344572-03\',\'2018-04-04 11:57:38.344603-03\',' +
            '1,0,1,-2000,0,0,0,0,0);'
        ),
    ]
