# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20180404_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdesign',
            name='name',
            field=models.CharField(default=b'horizontal layout', max_length=200, null=True),
        ),
    ]
