# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20180404_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.CharField(max_length=1000),
        ),
    ]
