# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_auto_20180405_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='custom_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
