# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_auto_20180405_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
