# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0013_event_evb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evb_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
