# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_auto_20180407_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='evb_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
