# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0015_event_evb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdesign',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
