# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_eventdesign_html'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO '
            'banner_eventdesign("name","created","changed","user_id","html") '
            'VALUES (\'default\',\'2018-04-04 11:57:38'
            '.344572-03\',\'2018-04-04 11:57:38.344603-03\','
            '1,\''
            '<div class="panel-event">'
            '<div class="panel-event-header row">'
            '<div class="col-md-8 event-logo" style="padding: 0'
            '!important;">'
            '<img class="img-rounded"'
            'src="|| logo ||" />'
            '</div>'
            '<div class="col-md-4 info-panel" style="padding-left: 0'
            '!important;">'
            '<div class="event-start-date-month">'
            '|| startdate_month ||'
            '</div>'
            '<div class="event-start-date-day">'
            '|| startdate_day ||'
            '</div>'
            '<div class="event-title">'
            '|| title ||'
            '</div>'
            '</div>'
            '</div>'
            '<div class="panel-event-body">'
            '<div class="row box">'
            '<div class="col-md-8" style="padding: 0 !important;">'
            '<div class="event-description">'
            '|| description ||'
            '</div>'
            '</div>'
            '<div class="col-md-4" style="padding: 0 !important;">'
            '<div class="event-qr" id="qrcode-|| id ||"></div>'
            '</div>'
            '</div>'
            '</div>'
            '</div>\');'
        )
    ]
